### ISSUE TITLE
the gdrive doc requires permission

### ISSUE THREAD

**Issue by mh-cbon** [davecheney/benchjuju#4]
hi,

is it possible to have read access for anyone ?

also that link is broken,
https://github.com/davecheney/benchjuju/blob/master/rsc.io/benchstat

thanks

**Comment by davecheney** [comment]
I'm not updating that document any more. Sorry

**Comment by mh-cbon** [comment]
sure. Does it mean the effort described here is not interesting ?
https://groups.google.com/forum/#!topic/golang-nuts/i92pOQ9DuAc
Is there a place to to know more about such figures ?

thanks

**Comment by davecheney** [comment]
I think the answer is probably likely to be more cores is better than fewer faster cores.

> On 19 Apr 2017, at 20:56, mh-cbon <notifications@github.com> wrote:
> 
> sure. Does it mean the effort described here is not interesting ?
> https://groups.google.com/forum/#!topic/golang-nuts/i92pOQ9DuAc
> Is there a place to to know more about such figures ?
> 

I don't know what you are asking. Sorry.
